#!/bin/sh

ENABLED=$(git config zeitgit.enabled)

if [ "$ENABLED" = "" ] ; then
	echo "Zeitgit not configured!"
	exit 127
fi

if [ "$ENABLED" = "0" ] ; then
	echo "Zeitgit not enabled"
	exit
fi

ORIGIN=$(git config remote.origin.url) || ORIGIN=local
BRANCH=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/') || BRANCH=unknown
EMAIL=$(git config zeitgit.email)

if [ "$EMAIL" = "" ] ; then
	echo "Zeitgit not configured!"
	exit 127
fi

FORMAT="ORIGIN $ORIGIN%nBRANCH $BRANCH%nHASH %H%nTREEHASH %T%nPARENTHASH %P%nAUTHORNAME %aN%nAUTHOREMAIL %aE%nAUTHORDATE %at%nCOMMITERNAME %cN%nCOMMITEREMAIL %cE%nCOMMITERDATE %ct%nSUBJECT %s%nBODY %b%n"

git log -C -1 --stat --summary --no-color "--pretty=tformat:$FORMAT" | mail -sgitcommit $EMAIL
